name: Release-candidate automation

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

concurrency:
  group: release-candidate-automation

jobs:
  compute-build-info:
    runs-on: ubuntu-latest

    outputs:
      latest_tag: ${{ steps.build-info.outputs.latest_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compute build info
        id: build-info
        shell: bash
        run: |
          version=${GITHUB_REF#refs/*/}
          echo $version
          echo "::set-output name=latest_tag::$version"

  build-and-publish-docker-image:
    runs-on: ubuntu-latest

    needs: compute-build-info

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Vault Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULTURL }}
          token: ${{ secrets.VAULTTOKEN }}
          caCertificate: ${{ secrets.VAULTCA }}
          secrets: |
              debio_production/data/frontend_dashboard vue_app_dai_contract_address;
              debio_production/data/frontend_dashboard vue_app_debio_backend_url;
              debio_production/data/frontend_dashboard vue_app_dev_debio_backend_url;
              debio_production/data/frontend_dashboard vue_app_dev_debio_escrow_eth_address;
              debio_production/data/frontend_dashboard vue_app_dev_debio_substrate_ws;
              debio_production/data/frontend_dashboard vue_app_dev_debio_use_token_name;
              debio_production/data/frontend_dashboard vue_app_dev_url_faucet;
              debio_production/data/frontend_dashboard vue_app_dev_web3_rpc;
              debio_production/data/frontend_dashboard vue_app_recaptcha_site_key;
              debio_production/data/frontend_dashboard vue_app_role;
              debio_production/data/frontend_file file_data | FILE_DATA;
              debio_production/data/frontend_file file_name | FILE_NAME;
              debio_production/data/frontend_file path | FILE_PATH;

      - name: Create .env
        shell: bash
        run: |
          tee -a .env <<EOF
          VUE_APP_DAI_CONTRACT_ADDRESS=$VUE_APP_DAI_CONTRACT_ADDRESS
          VUE_APP_DEBIO_BACKEND_URL=$VUE_APP_DEBIO_BACKEND_URL
          VUE_APP_DEV_DEBIO_BACKEND_URL=$VUE_APP_DEV_DEBIO_BACKEND_URL
          VUE_APP_DEV_DEBIO_ESCROW_ETH_ADDRESS=$VUE_APP_DEV_DEBIO_ESCROW_ETH_ADDRESS
          VUE_APP_DEV_DEBIO_SUBSTRATE_WS=$VUE_APP_DEV_DEBIO_SUBSTRATE_WS
          VUE_APP_DEV_DEBIO_USE_TOKEN_NAME=$VUE_APP_DEV_DEBIO_USE_TOKEN_NAME
          VUE_APP_DEV_URL_FAUCET=$VUE_APP_DEV_URL_FAUCET
          VUE_APP_DEV_WEB3_RPC=$VUE_APP_DEV_WEB3_RPC
          VUE_APP_RECAPTCHA_SITE_KEY=$VUE_APP_RECAPTCHA_SITE_KEY
          VUE_APP_ROLE=$VUE_APP_ROLE
          EOF

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-main
          restore-keys: |
            ${{ runner.os }}-buildx-

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          # file: .maintain/docker/Dockerfile
          tags: |
            hub.debio.network/debio_frontend_revamp:${{ needs.compute-build-info.outputs.latest_tag }}
            hub.debio.network/debio_frontend_revamp:latest-rc
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    runs-on: ubuntu-latest

    needs: [compute-build-info, build-and-publish-docker-image]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: reload service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop debio_frontend_revamp_rc || true && docker rm debio_frontend_revamp_rc || true
            docker pull hub.debio.network/debio_frontend_revamp:${{ needs.compute-build-info.outputs.latest_tag }}
            docker run -d --name=debio_frontend_revamp_rc --env=debioenv=development -v /etc/localtime:/etc/localtime:ro -p 0.0.0.0:8088:80 --restart=always hub.debio.network/debio_frontend_revamp:${{ needs.compute-build-info.outputs.latest_tag }}
